add %rax %rbx %rcx
add %rax %rbx 42

sub %rax %rbx %rcx
sub %rax %rbx 42

or %rax %rbx %rcx
or %rax %rbx 42

nand %rax %rbx %rcx
nand %rax %rbx 42

xor %rax %rbx %rcx
xor %rax %rbx 42

nxor %rax %rbx %rcx
nxor %rax %rbx 42

and %rax %rbx %rcx
and %rax %rbx 42

nor %rax %rbx %rcx
nor %rax %rbx 42

sll %rax %rbx %rcx
sll %rax %rbx 42

srl %rax %rbx %rcx
srl %rax %rbx 42

sra %rax %rbx %rcx
sra %rax %rbx 42

seq %rax %rbx %rcx
seq %rax %rbx 42

slt %rax %rbx %rcx
slt %rax %rbx 42